// <auto-generated />
namespace YHRSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Nineth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nineth));
        
        string IMigrationMetadata.Id
        {
            get { return "201503211338573_Nineth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
